<?php
$activationBlockObj = Mage::getBlockSingleton('activation/activation');
if (($activationBlockObj->raasEnable() == 0) && ($this->showDefault() == 1)) {
    if ($this->isLoggedIn()) {
        echo '<div class="block"><div class="block-title"><strong><span>' . $this->titleInterface() . '</span></strong></div><div class="block-content"><p class="empty">';
        if ($loginRadiusAvatar = trim($this->getAvatar(Mage::getSingleton('customer/session')->getCustomer()->getId()))) {
            echo "<img style='float:left' width='50' height='50' src='" . $loginRadiusAvatar . "' />";
        }
        echo "<span style='clear:both;'>" . __("Welcome") . "!  " . Mage::getSingleton('customer/session')->getCustomer()->getName() . " </span>";
        echo '</p><a href="'.Mage::getUrl('customer/account').'">'.__('My Account').'</a></div><div style="clear:both;"></div><div class="actions"><a href="'.Mage::getUrl('customer/account/logout').'"><button class="button">'.__('Log Out').'</button></a></div></div>';
    } else {
        echo $this->getSocialLoginContainer();
    }
}