<?php

$activationHelper = $this->helper('LoginRadius\Activation\Model\Helper\Data');
include_once('function.php');

if ($activationHelper->siteApiKey() != '' && $activationHelper->siteApiSecret() != '') {     
        $decryptedSecretKey = lr_secret_encrypt_and_decrypt($activationHelper->siteApiSecret(), $activationHelper->siteApiKey(), 'd');   
         $phoneLoginEnabled = $activationHelper->phoneLoginEnabled();
        ?>
        <script type="text/javascript">
        
            var secretkey = '<?php echo $decryptedSecretKey?>';   
            var phoneLoginEnabled = '<?php echo $phoneLoginEnabled?>';        
          
        </script>
        <?php
}?>