<?php
$activationHelper = $this->helper('LoginRadius\Activation\Model\Helper\Data');
if ($activationHelper->siteApiKey() != '' && $activationHelper->siteApiSecret() != '') {
    $customerRegistrationHelper = $this->helper('LoginRadius\CustomerRegistration\Model\Helper\Data');
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');

    if ($customerRegistrationHelper->checkoutRedirection() == 'onlogin') {
        $customerSession = $objectManager->get('Magento\Customer\Model\Session');
        if (!$customerSession->isLoggedIn()) {
            $customerSession->setLoginRadiusRedirection('checkout');
            ?>
            <script>
                window.location.href = '<?php echo $this->getUrl('customer/account/login'); ?>';
            </script>
            <?php
        } else {
            $customerSession->unsLoginRadiusRedirection();
        }
    } else if($customerRegistrationHelper->checkoutRedirection() == 'oncheckout'){
        if (!$customerSession->isLoggedIn()) {
            ?>
            <main id="maincontent" class="page-main">
                <div id="loginradiusmessagediv"></div>
                <div class="columns">
                    <div id="login_form">
                        <div class="page-title-wrapper">
                            <h1 class="page-title">
                                <span class="base" data-ui-id="page-title-wrapper"><?php echo __('Customer Login') ?></span>  
                            </h1>
                        </div>
                        <fieldset class="fieldset create info account form-create-account">
                            <div style="margin:5px"></div><div class="lr_embed_bricks_200 interfacecontainerdiv" id="interfacecontainerdiv" ></div>
                        </fieldset>
                        <?php echo $block->getBlockHtml('formkey'); ?>
                        <div class="login-container">
                            <div class="block block-customer-login">
                                <div class="block-title">
                                    <strong id="block-customer-login-heading" role="heading" aria-level="2"><?php echo __('Login Customers') ?></strong>
                                </div>
                                <div class="block-content" aria-labelledby="block-customer-login-heading">
                                    <div id="login-container"></div>
                                    <div class="ciamforgotpassword primary">
                                        <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>"><span><?php echo __('Forgot Password') ?></span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="required_form">
                        <div class="page-title-wrapper">
                            <h1 class="page-title">
                                <span class="base" data-ui-id="page-title-wrapper"><?php echo __('Customer Login') ?></span>  
                            </h1>
                        </div>
                        <div id="social-registration-container"></div>
                    </div>
                    <div id="reset_form" style="display: none;">
                        <div class="page-title-wrapper">
                            <h1 class="page-title">
                                <span class="base" data-ui-id="page-title-wrapper"><?php echo __('Reset Password') ?></span>  
                            </h1>
                        </div>
                        <div id="resetpassword-container"></div>
                    </div>
                </div>
            </main>
            <script>
                require(['jquery', "mage/calendar"], function ($) {
                    ciamForm.login();
                    ciamForm.interface();
                    ciamForm.socialLogin();
                    showformbyId("login_form");
                    ciamForm.resetPassword();
                    responseHandler(true);
                });
            </script>
            <script type="text/html" id="loginradiuscustom_tmpl">
                <div class="lr_icons_box">
                    <div style="width:180px">
                        <span class="lr_providericons lr_<#=Name.toLowerCase()#>  lr-icon-<#=Name.toLowerCase()#>" onclick="return $SL.util.openWindow('<#= Endpoint #>&is_access_token=true&callback=<?php echo $this->getUrl() ?>');" title="<#= Name #>" alt="Sign in with <#=Name#>">
                        </span>
                    </div>
                </div>
            </script>
            <?php
        } else {
            $customerSession->unsLoginRadiusRedirection();
        }
        ?>
        <script>
            require(['jquery'], function ($) {
                $(document).ready(function () {
                    $('#ciam-loading-image-div').hide();
                });
            });
        </script>
        <?php
    }
}