<?php
$activationHelper = $this->helper('LoginRadius\Activation\Model\Helper\Data');
if ($activationHelper->siteApiKey() != '' && $activationHelper->siteApiSecret() != '') {
    /** @var \Magento\Customer\Block\Form\Edit $block */
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
// Social API's
    $userAPI = new \LoginRadiusSDK\CustomerRegistration\UserAPI($activationHelper->siteApiKey(), $activationHelper->siteApiSecret(), array('authentication' => true, 'output_format' => 'json'));
    try {
        $responce = $userAPI->getProfileByEmail($block->escapeHtml($customerSession->getCustomer()->getEmail()));
    } catch (\LoginRadiusSDK\LoginRadiusException $e) {
        $this->_eventManager->dispatch('lr_logout_sso', array('exception' => $e));
    }

    $showPasswordForm = false;
    if (isset($responce)) {
        foreach ($responce as $k => $val) {
            if ((isset($val->Provider) && strtolower($val->Provider) == 'raas') || (isset($val->EmailVerified) && $val->EmailVerified == true)) {
                $showPasswordForm = true;
                break;
            }
        }
    }
    ?>
    <div id="loginradiusmessagediv"></div>
    <form class="form form-edit-account" action="<?php /* @escapeNotVerified */ echo $block->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" autocomplete="off">
        <fieldset class="fieldset info">
            <?php echo $block->getBlockHtml('formkey') ?>
            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Account Information') ?></span></legend><br>
            <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($customerSession->getCustomer())->toHtml() ?>
            <div class="field email required">
                <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                <div class="control">
                    <input type="email" readonly="readonly" name="email" id="email" value="<?php echo $block->escapeHtml($customerSession->getCustomer()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>
            <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
            <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
            <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
            <?php if ($_dob->isEnabled()): ?>
                <?php echo $_dob->setDate($customerSession->getCustomer()->getDob())->toHtml() ?>
            <?php endif ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <?php echo $_taxvat->setTaxvat($customerSession->getCustomer()->getTaxvat())->toHtml() ?>
            <?php endif ?>
            <?php if ($_gender->isEnabled()): ?>
                <?php echo $_gender->setGender($customerSession->getCustomer()->getGender())->toHtml() ?>
            <?php endif ?>
            <?php 
            if ($showPasswordForm) { ?>
                <div class="field choice">
                    <input type="checkbox" name="changepassword" onclick="setPasswordForm(this.checked)" id="changepassword" value="1" title="<?php /* @escapeNotVerified */ echo __('Change Password') ?>"<?php if ($customerSession->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox"/>
                    <label class="label" for="changepassword"><span><?php /* @escapeNotVerified */ echo __('Change Password') ?></span></label>
                </div>
            <?php } ?>
        </fieldset>
        
        <?php if ($showPasswordForm) { ?>
            <fieldset class="fieldset password" style="display:none;" id="socialpasswordbox">
                <legend class="legend"><span id="changepasswordtitle"><?php /* @escapeNotVerified */ echo __('Change Password') ?></span></legend><br>
                <div id="changepasswordbox" style="display:none"></div>
                <div id="setpasswordbox" style="display:none"></div>
            </fieldset>
        <?php } ?>
        <div style="clear:both"></div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary" title="<?php /* @escapeNotVerified */ echo __('Save') ?>"><span><?php /* @escapeNotVerified */ echo __('Save') ?></span></button>
            </div>
            <div class="secondary">
                <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
            </div>
        </div>
    </form>
    <script>
                require([
                        "jquery",
                        "mage/mage",
                        "mage/calendar"
                ], function($){
                var dataForm = $('#form-validate');
                        var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;
                        dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()): ?>
                            errorPlacement: function(error, element) {
                            if (element.prop('id').search('full') !== - 1) {
                            var dobElement = $(element).parents('.customer-dob'),
                                    errorClass = error.prop('class');
                                    error.insertAfter(element.parent());
                                    dobElement.find('.validate-custom').addClass(errorClass)
                                    .after('<div class="' + errorClass + '"></div>');
                            }
                            else {
                            error.insertAfter(element);
                            }
                            },
                                    ignore: ':hidden:not(' + ignore + ')'
    <?php else: ?>
                            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
                        });
                        raasForm.accountPassword();
                        responseHandler(true);
    <?php if ($customerSession->getChangePassword()): ?>
                    setPasswordForm(true);
    <?php endif; ?>
                });
    </script>
<?php } ?>
