<?php
$activationHelper = $this->helper('LoginRadius\Activation\Model\Helper\Data');
if ($activationHelper->siteApiKey() != '' && $activationHelper->siteApiSecret() != '') {
    $customerRegistrationHelper = $this->helper('LoginRadius\CustomerRegistration\Model\Helper\Data');
    ?>
    <main id="maincontent" class="page-main">
        <div class="page-title-wrapper">
            <h1 class="page-title">
                <span class="base" data-ui-id="page-title-wrapper"><?php echo __('Forgot Your Password'); ?></span>  
            </h1>
        </div>
        <div id="loginradiusmessagediv"></div>
        <div class="columns">
            <div>
                <div id="forgotpassword-container"></div>
            </div>
        </div>
    </main>

    <script>
        require(['jquery',"mage/calendar"], function ($) {
            raasForm.forgotPassword();
            responseHandler(true);
        });
    </script>
<?php
}?>