<?php
$singleSignOnHelper = $this->helper('LoginRadius\SingleSignOn\Model\Helper\Data');
$activationHelper = $this->helper('LoginRadius\Activation\Model\Helper\Data');
if ($singleSignOnHelper->enableSinglesignon() == '1' && $activationHelper->siteApiKey() != '' && $activationHelper->siteApiSecret() != '') {
    $ssoRootUrl = parse_url($this->getUrl(''));
    $ssoRootUrl['path'] = isset($ssoRootUrl['path']) ? trim(trim($ssoRootUrl['path'], "/")) : '';
    $ssoTempDir = explode("/", $ssoRootUrl['path']);
    $ssoPath = isset($ssoTempDir[0]) ? '/' . trim($ssoTempDir[0]) . '/' : '';
    ?>
    <script type="text/javascript">
        require(['jquery'], function ($) {
            $(document).ready(function () {
    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
    if ($customerSession->isLoggedIn()) {//user logged in
        ?>
                    var check_options = {};
                    check_options.onError = function (response) {
                        // On Error
                        // If user is not log in then this function will execute.
                        window.location = "<?php echo html_entity_decode($this->getUrl('customer/account/logout')); ?>";
                    };
                    check_options.onSuccess = function (response) {
                        // On Success
                        // If user is log in then this function will execute.
                    };
                    LRObject.init("ssoNotLoginThenLogout", check_options);
                    if ($('a[href*="logout"]').length > 0) {
                        var href = $('a[href*="logout"]').attr('href');
                        $('a[href*="logout"]').attr('onclick', "return false;");
                        $('a[href*="logout"]').click(function (e) {
                            $('body').prepend('<div id="ciam-loading-image-div" style="width:100%;"><div class="loadinternal"></div></div>');
                            e.preventDefault();
                            var logout_options = {};
                            logout_options.onSuccess = function () {
                                window.location.href = href;
                                // On Success
                                //Write your custom code here
                            };
                            LRObject.init("logout", logout_options);
                        });
                    }
    <?php } else { ?>

                    var ssologin_options = {};
                    ssologin_options.onSuccess = function (token) {
                        var form = document.createElement('form');
                        form.action = "<?php echo $this->getUrl("customerregistration/auth/") ?>";
                        form.method = 'POST';
                        var hiddenToken = document.createElement('input');
                        hiddenToken.type = 'hidden';
                        hiddenToken.value = token;
                        hiddenToken.name = 'token';
                        form.appendChild(hiddenToken);
                        document.body.appendChild(form);
                        form.submit();
                    };
                    LRObject.init("ssoLogin", ssologin_options);
    <?php } ?>

            });
        });
    </script>
    <?php
} 