<?php
/**
 * template to add script required for social sharing
 */
if ($this->horizontalShareEnable() == "1" || $this->verticalShareEnable() == "1") {
    ?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('../../../adminhtml/default/default/Loginradius/socialshare/js/socialshare.js') ?>"></script>
    <?php
    $sharingScript = '<script type="text/javascript">';
    if ($this->horizontalShareEnable() == "1") {
        $shareType = '';
        $sharingScript .= 'var shareWidget = new OpenSocialShare();';
        $sharingScript .= 'shareWidget.init({';
        $sharingScript .= 'isHorizontalLayout: 1,';
        $sharingTheme = $this->horizontalSharingTheme();
        switch ($sharingTheme) {
            case 'responsive':
                $sharingScript .= 'widgetIconSize: "32",';
                $sharingScript .= 'widgetStyle: "responsive",';
                $shareType = 'share';
                break;
            case '16':
                $sharingScript .= 'widgetIconSize: "16",';
                $sharingScript .= 'widgetStyle: "square",';
                $shareType = 'share';
                break;
            case 'single_large':
                $sharingScript .= 'widgetIconSize: "32",';
                $sharingScript .= 'widgetStyle: "image",';
                $shareType = 'image';
                break;
            case 'single_small':
                $sharingScript .= 'widgetIconSize: "16",';
                $sharingScript .= 'widgetStyle: "image",';
                $shareType = 'image';
                break;
            case 'counter_horizontal':
                $sharingScript .= 'isCounterWidgetTheme: 1,';
                $sharingScript .= 'isHorizontalCounter: 1,';
                $shareType = 'counter';
                break;
            case 'counter_vertical':
                $sharingScript .= 'isCounterWidgetTheme: 1,';
                $sharingScript .= 'isHorizontalCounter: 0,';
                $shareType = 'counter';
                break;
            default :
                $sharingScript .= 'widgetIconSize: "32",';
                $sharingScript .= 'widgetStyle: "square",';
                $shareType = 'share';
        }

        if (($shareType == 'share') || ($shareType == 'image')) {
            if ($shareType == 'share') {
                $sharingScript .= 'isMobileFriendly: ' . $this->isMobileFriendly() . ',';
                $sharingScript .= 'isTotalShare: ' . $this->totalShare() . ',';
            }
           
            $sharingScript .= 'isEmailContentReadOnly: ' . $this->emailReadOnly() . ',';
            $sharingScript .= ($this->emailSubject() != '') ? ('emailSubject: "' . $this->emailSubject() . '",') : '';
            $sharingScript .= ($this->emailMessage() != '') ? ('emailMessage: "' .trim(preg_replace('/\s\s+/', ' ',$this->emailMessage())) . '",') : '';
            $sharingScript .= 'isShortenUrl: ' . $this->shortUrl() . ',';
            $sharingScript .= 'isOpenSingleWindow: ' . $this->samePopup() . ',';
            if (($this->popupWidth() != '') && ($this->popupHeight() != '')) {
                $sharingScript .= "popupWindowSize:{height:" . $this->popupHeight() . ",width :" . $this->popupWidth() . "},";
            }
            $sharingScript .= ($this->facebookAppId() != '') ? ('facebookAppId: "' . $this->facebookAppId() . '",') : '';
            $sharingScript .= ($this->twitterMention() != '') ? ('twittermention: "' . $this->twitterMention() . '",') : '';
            $sharingScript .= ($this->twitterHash() != '') ? ('twitterhashtag: "' . $this->twitterHash() . '",') : '';
        }
        
        if($this->customOptions() != ''){
            $customOption = json_decode($this->customOptions(), true);
            if(!is_array($customOption)){
                $sharingScript .= htmlentities($this->customOptions());
            }else{
                foreach($customOption as $key => $value){
                    $sharingScript .= $key.': '.(is_array($value)?json_encode($value):"'".$value."'").',';
                }
            }
        }
    
        $sharingScript .= 'theme: \'OpenSocialShareDefaultTheme\',';
        $sharingScript .= $this->getSelectedSocialProvider('horizontal', $shareType);
        $sharingScript = substr($sharingScript, 0, -1);
        $sharingScript .= '});';
        $sharingScript .= 'shareWidget.injectInterface(".openSocialShareHorizontalSharing");';
        $sharingScript .= 'shareWidget.setWidgetTheme(".openSocialShareHorizontalSharing");';
        ?>
        <style>
            .openSocialShareHorizontalSharing {
                clear: both;
            }
        </style>
        <?php
    }
    // vertical sharing interface
    if ($this->verticalShareEnable() == "1") {
        $shareType = '';
        $sharingScript .= 'var shareWidget = new OpenSocialShare();';
        $sharingScript .= 'shareWidget.init({';
        $sharingScript .= 'isHorizontalLayout: 0,';
        $verticalShareTheme = $this->verticalSharingTheme();
        switch ($verticalShareTheme) {
            case 'counter_horizontal':
                $sharingScript .= 'isCounterWidgetTheme: 1,';
                $sharingScript .= 'isHorizontalCounter: 1,';
                $shareType = 'counter';
                break;
            case 'counter_vertical':
                $sharingScript .= 'isCounterWidgetTheme: 1,';
                $sharingScript .= 'isHorizontalCounter: 0,';
                $shareType = 'counter';
                break;
            case '16':
                $sharingScript .= 'widgetIconSize: "16",';
                $sharingScript .= 'widgetStyle: "square",';
                $shareType = 'share';
                break;
            default :
                $sharingScript .= 'widgetIconSize: "32",';
                $sharingScript .= 'widgetStyle: "square",';
                $shareType = 'share';
        }

        if ($shareType == 'share') {
            $sharingScript .= 'isEmailContentReadOnly: ' . $this->emailReadOnly() . ',';
            $sharingScript .= ($this->emailSubject() != '') ? ('emailSubject: "' . $this->emailSubject() . '",') : '';
            $sharingScript .= ($this->emailMessage() != '') ? ('emailMessage: "' . trim(preg_replace('/\s\s+/', ' ',$this->emailMessage())) . '",') : '';
            $sharingScript .= 'isShortenUrl: ' . $this->shortUrl() . ',';
            $sharingScript .= 'isTotalShare: ' . $this->totalShare() . ',';
            $sharingScript .= 'isOpenSingleWindow: ' . $this->samePopup() . ',';
            $sharingScript .= ($this->facebookAppId() != '') ? ('facebookAppId: "' . $this->facebookAppId() . '",') : '';
            $sharingScript .= ($this->twitterMention() != '') ? ('twittermention: "' . $this->twitterMention() . '",') : '';
            $sharingScript .= ($this->twitterHash() != '') ? ('twitterhashtag: "' . $this->twitterHash() . '",') : '';
            if (($this->popupWidth() != '') && ($this->popupHeight() != '')) {
                $sharingScript .= "popupWindowSize:{height:" . $this->popupHeight() . ",width :" . $this->popupWidth() . "},";
            }
        }

        if($this->customOptions() != ''){
            $customOption = json_decode($this->customOptions(), true);
            if(!is_array($customOption)){
                $sharingScript .= htmlentities($this->customOptions());
            }else{
                foreach($customOption as $key => $value){
                    $sharingScript .= $key.': '.(is_array($value)?json_encode($value):"'".$value."'").',';
                }
            }
        }
        
        $sharingScript .= 'theme: \'OpenSocialShareDefaultTheme\',';
        $sharingScript .= $this->getSelectedSocialProvider('vertical', $shareType);
        $sharingScript = substr($sharingScript, 0, -1);
        $sharingScript .= '});';
        $sharingScript .= 'shareWidget.injectInterface(".openSocialShareVerticalSharing");';
        $sharingScript .= 'shareWidget.setWidgetTheme(".openSocialShareVerticalSharing");';
        $alignment = $this->verticalAlignment();
        switch ($alignment) {
            case 'top_right':
                $style = '<style>.openSocialShareVerticalSharing {position: fixed;top:0px;right:0px;}</style>';
                break;
            case 'bottom_right':
                $style = '<style>.openSocialShareVerticalSharing {position: fixed;bottom:0px;right:0px;}</style>';
                break;
            case 'bottom_left':
                $style = '<style>.openSocialShareVerticalSharing {position: fixed;bottom:0px;left:0px;}</style>';
                break;
            default:
                $style = '<style>.openSocialShareVerticalSharing {position: fixed;top:0px;left:0px;}</style>';
        }
        echo $style;
    }
    $sharingScript .= '</script>';
    echo $sharingScript;
}