<?php

if ($this->isLoggedIn()) {
    if (Mage::getBlockSingleton('activation/activation')->raasEnable() == '1') {
        echo $this->getLayout()->createBlock('sociallogin/sociallogin')->setTemplate('Loginradius/customerregistration/resetpassword.phtml')->toHtml();
    } else {
        echo $this->getLayout()->createBlock('customer/account_resetpassword')->setTemplate('customer/form/resetforgottenpassword.phtml')->toHtml();
    }
}