<?php
$activationHelper = $this->helper('LoginRadius\Activation\Model\Helper\Data');
if ($activationHelper->siteApiKey() != '' && $activationHelper->siteApiSecret() != '') {
    $customerRegistrationHelper = $this->helper('LoginRadius\CustomerRegistration\Model\Helper\Data');
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
    $eventManager = $objectManager->get('\Magento\Framework\Event\Manager');
        new \LoginRadiusSDK\Utility\Functions($activationHelper->siteApiKey(), $activationHelper->siteApiSecret(), array('output_format' => 'json'));
        $sott = new \LoginRadiusSDK\Utility\SOTT();
        $currentURL = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
        $callBackURL = $this->getUrl("customerregistration/auth/");
        if ($customerRegistrationHelper->getValueFromStringUrl($currentURL, 'redirect_to')) {
            $callBackURL .= '?redirect_to=' . $customerRegistrationHelper->getValueFromStringUrl($currentURL, 'redirect_to');
        }
        $parseURL = parse_url($currentURL);
        if (isset($parseURL['host']) && !empty($parseURL['host']) && isset($_SERVER["HTTP_REFERER"]) && (strpos($_SERVER["HTTP_REFERER"], $parseURL['host']) !== false)) {
            $customerSession->setRefererURLData($_SERVER["HTTP_REFERER"]);
        }
        ?>
        <script type="text/javascript">
            //initialize raas options
            var LocalDomain = '<?php echo $callBackURL; ?>';
            var SignInDomain = '<?php echo $this->getUrl("customer/account/login/") ?>';

            var commonOptions = {};
            commonOptions.apiKey = "<?php echo $activationHelper->siteApiKey(); ?>";
            commonOptions.appName = "<?php echo htmlentities($activationHelper->siteName()); ?>";
            commonOptions.hashTemplate = true;
            commonOptions.sott = "<?php echo urlencode($sott->encrypt()); ?>";
            commonOptions.verificationUrl = "<?php echo $this->getUrl('customerregistration/verification') ?>";
            commonOptions.resetPasswordUrl = '<?php echo $this->getUrl('customer/account/login') ?>';
            commonOptions.forgotPasswordUrl = '<?php echo $this->getUrl('customer/account/login') ?>';
            commonOptions.formValidationMessage = <?php echo ($customerRegistrationHelper->formValidationMessage() == '1') ? "true" : "false" ?>;
        <?php if ($customerRegistrationHelper->termsConditions() != '') { ?>
                commonOptions.termsAndConditionHtml = '<?php echo str_replace(array("'", '<script>', '</script>'), array('"', '', ''), $customerRegistrationHelper->termsConditions()); ?>';
        <?php } if ($customerRegistrationHelper->delayTime() != '') { ?>
                commonOptions.formRenderDelay = <?php echo (int) $customerRegistrationHelper->delayTime(); ?>;
        <?php } if (($customerRegistrationHelper->minPassword() != $customerRegistrationHelper->maxPassword()) && ($customerRegistrationHelper->minPassword() != '') && ($customerRegistrationHelper->maxPassword() != '')) { ?>
                commonOptions.passwordlength = {
                    "min":<?php echo $customerRegistrationHelper->minPassword(); ?>,
                    "max":<?php echo $customerRegistrationHelper->maxPassword(); ?>
                };
        <?php } if ($customerRegistrationHelper->emailVerification() == '0') { 
                if($customerRegistrationHelper->promptPasswordOnSocialLogin() == '1'){?>
                commonOptions.promptPasswordOnSocialLogin = true;
        <?php } if($customerRegistrationHelper->loginUponEmailVerification() == '1'){?>        
                commonOptions.loginOnEmailVerification = true;
        <?php } if($customerRegistrationHelper->usernameLogin() == '1'){?>        
                commonOptions.usernameLogin = true;
        <?php } if($customerRegistrationHelper->alwaysAskEmailForUnverified() == '1'){?>        
                commonOptions.askEmailForUnverifiedProfileAlways = true;
        <?php }} if ($customerRegistrationHelper->emailVerification() == '2') { 
                 if($customerRegistrationHelper->loginUponEmailVerification() == '1'){?>        
                commonOptions.loginOnEmailVerification = true;
        <?php } if($customerRegistrationHelper->alwaysAskEmailForUnverified() == '1'){?>        
                commonOptions.askEmailForUnverifiedProfileAlways = true;
        <?php }} if ($customerRegistrationHelper->forgotEmail() != '') { ?>
                commonOptions.forgotPasswordTemplate = "<?php echo htmlentities($customerRegistrationHelper->forgotEmail()); ?>";
        <?php } if ($customerRegistrationHelper->verificationEmail() != '') { ?>
                commonOptions.verificationEmailTemplate = "<?php echo htmlentities($customerRegistrationHelper->verificationEmail()); ?>";
        <?php }?>
            commonOptions.disabledEmailVerification = <?php echo ($customerRegistrationHelper->emailVerification() == '1') ? "true" : "false" ?>;
            commonOptions.optionalEmailVerification = <?php echo ($customerRegistrationHelper->emailVerification() == '2') ? "true" : "false" ?>;
            commonOptions.debugMode = <?php echo ($customerRegistrationHelper->debug() == '1') ? "true" : "false" ?>;
           <?php echo $eventManager->dispatch('ciam_options', array('exception' => ''));?>
            var LRObject = new LoginRadiusV2(commonOptions);
        <?php
        if ($customerRegistrationHelper->customJsOptions() != '' && $customerRegistrationHelper->customJsOptions() != 'null' && $customerRegistrationHelper->customJsOptions() != null) {
            $lrCustomOption = json_decode($customerRegistrationHelper->customJsOptions(), true);
            if (!is_array($lrCustomOption)) {
                echo $customerRegistrationHelper->customJsOptions();
            } else {
                foreach ($lrCustomOption as $lrkey => $lrvalue) {
                    echo 'commonOptions.' . $lrkey . ' = ' . (is_array($lrvalue) ? json_encode($lrvalue) : "'" . $lrvalue . "'") . ';';
                }
            }
        }
        ?>
            require(['jquery'], function ($) {
                $(document).ready(function () {
                    if (commonOptions.optionalEmailVerification) {
                        commonOptions.optionalEmailVerification = <?php echo ($customerSession->getLoginRadiusEmailVerified() == '1') ? "false" : "true" ?>;
                    }
                    if (commonOptions.optionalEmailVerification || commonOptions.disabledEmailVerification) {
                        if ($('a[href*="customerregistration/accounts/linking"]').length > 0) {
                            $('a[href*="customerregistration/accounts/linking"]').parent().remove();
                            $('#ciam-loading-image-div').hide();
                        }
                    }
                });
            });
        </script>
        <?php
        if (!$customerSession->isLoggedIn()) {
            ?>
            <script type="text/html" id="loginradiuscustom_tmpl">
                <div class="lr_icons_box">
                    <div style="width:180px">
                        <span class="lr_providericons lr_<#=Name.toLowerCase()#>  lr-icon-<#=Name.toLowerCase()#>" onclick="return <#=ObjectName#>.util.openWindow('<#= Endpoint #>');" title="<#= Name #>" alt="Sign in with <#=Name#>">
                        </span>
                    </div>
                </div>
            </script>
        <?php } else { ?>
            <script type="text/html" id="loginradiuscustom_tmpl_link">
                <# if(isLinked) { #>
                <div class="lr-linked">
                    <div class="lr-linked-id"><span class="lr-icon-frame">
                            <span class="lr-icon lr-raas-<#= Name.toLowerCase() #>">
                            </span>
                        </span>
                        <div class="lr-linked-image lr-icon-<#= Name.toLowerCase() #> lr-linked-provider" style="float:left;padding-right:30px;"></div>
                        <# if(providerId == "<?php echo $customerSession->getLoginRadiusId(); ?>" ) { #>
                        <span class="lr-linked-image"><?php echo __(' is connected currently'); ?></span>
                        <# }  else {#>
                        <span class="lr-linked-image"><?php echo __(' is connected'); ?></span>
                        <a style="margin-left:15px" class="lr-unlink" onclick='return  <#=ObjectName#>.util.unLinkAccount(\"<#= Name.toLowerCase() #>\",\"<#= providerId #>\")'><?php echo __('Remove'); ?></a>
                        <# } #>
                    </div>
                </div>
                <# }  else {#>
                <div class="lr_icons_box">
                    <div class="lr_icons_inner_box" style="width:100%;">
                        <span class="lr_providericons lr_<#=Name.toLowerCase()#>  lr-icon-<#=Name.toLowerCase()#>" onclick="return  <#=ObjectName#>.util.openWindow('<#= Endpoint #>&callback=<?php echo $this->getUrl('customer/account') ?>');" title="<#= Name #>" alt="Sign in with <#=Name#>">
                        </span>
                    </div>
                </div>
                <# } #>
            </script>
        <?php
        }
    echo '<div id="ciam-loading-image-div"><div class="loadinternal"></div></div>';
}