<?php
$activationHelper = $this->helper('LoginRadius\Activation\Model\Helper\Data');
if ($activationHelper->siteApiKey() != '' && $activationHelper->siteApiSecret() != '') {
    $customerRegistrationHelper = $this->helper('LoginRadius\CustomerRegistration\Model\Helper\Data');
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
    ?>
    <div class="page-title-wrapper">
        <h1 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper"><?php echo __('Account Linking') ?></span>  
        </h1>
    </div>
    <div id="loginradiusmessagediv" class="loginradiusmessagediv"></div>
    <div class="columns">
        <fieldset class="fieldset create info account form-account-linking">
            <div style="margin:5px"></div><div class="lr_embed_bricks_200 interfacecontainerdiv" id="interfacecontainerdiv" ></div>
        </fieldset>
        <div style="clear:both;"></div>
    </div>
    <script>
        require(['jquery', "mage/calendar"], function ($) {
            $(document).ready(function () {
                ciamForm.accountLinking();
                ciamForm.accountUnlinking();
            });
        });
        require(['jquery'], function ($) {
            $(document).ready(function () {
    <?php
    $style = '';
    $status = $customerSession->getLoginRadiusStatus();
    $message = $customerSession->getLoginRadiusMessage();
    if (!empty($status) && !empty($message)) {
        $status = ($status == 'Success') ? 'true' : 'false';
        ?>
                    responseHandler(<?php echo $status; ?>, '<?php echo $message; ?>');
        <?php
        $style = '<style>#loginradiusmessagediv{display:block !important;}</style>';
        $customerSession->unsLoginRadiusStatus();
        $customerSession->unsLoginRadiusMessage();
    }
    ?>
            });
        });
    </script>
    <?php
    echo $style;
}
?>