<?php
$activationHelper = $this->helper('LoginRadius\Activation\Model\Helper\Data');
if ($activationHelper->siteApiKey() != '' && $activationHelper->siteApiSecret() != '') {
    $customerRegistrationHelper = $this->helper('LoginRadius\CustomerRegistration\Model\Helper\Data');
    ?>
    <main id="maincontent" class="page-main">
        <div id="register_form" >
            <div class="page-title-wrapper">
                <h1 class="page-title">
                    <span class="base" data-ui-id="page-title-wrapper"><?php echo __("Create New Customer Account"); ?></span>
                </h1>
            </div>
            <div id="loginradiusmessagediv"></div>
            <div class="columns">
                <div>
                    <fieldset class="fieldset create info account form-create-account">
                        <legend class="legend">
                            <span><?php
                                echo $customerRegistrationHelper->interfaceTitle();
                                ?></span>
                        </legend><br>
                        <div style="margin:5px"></div><div class="lr_embed_bricks_200 interfacecontainerdiv" id="interfacecontainerdiv" ></div>
                    </fieldset>
                </div>
                <div id="registeration-container"></div>
            </div>
        </div>
        <div id="required_form" style="display: none;">
            <div class="page-title-wrapper">
                <h1 class="page-title">
                    <span class="base" data-ui-id="page-title-wrapper"><?php echo __('Customer Login') ?></span>  
                </h1>
            </div>
            <div id="social-registration-container"></div>
        </div>
    </main>
    <script>
        require(['jquery', "mage/calendar"], function ($) {
            ciamForm.register();
            ciamForm.interface();
            ciamForm.socialLogin();
            responseHandler(true);
        });
    </script>
    <?php
}