<?php
$activationBlockObj = Mage::getBlockSingleton('activation/activation');
if($activationBlockObj->apiKey() != '' && $activationBlockObj->apiSecret() != ''){?>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<div class="account-create" id="reg_from">
    <div class="fieldset">
        <div id="lr_social_login_interface">
            <h2 class="legend"><?php echo Mage::getBlockSingleton('customerregistration/customerregistration')->titleInterface() ?></h2>
            <div class="loginradiusmessagediv" style="display:none;"></div>        
            <div class="magento-raas-loading-image-div"></div>
            <?php echo Mage::getBlockSingleton('customerregistration/customerregistration')->getSocialLoginContainer(); ?>
        </div>
        <div style="clear:both"></div>
        <h2 class="legend"><?php echo $this->__('CREATE AN ACCOUNT') ?></h2>
        <div id="registeration-container"></div>
        <div id="social_registration_from" class="account-login" style="display:none;">
            <h2 class="legend"><?php echo $this->__('Complete your profile') ?></h2>
            <div id="social-registration-container"></div>
        </div>
        <div class="buttons-set">
            <p class="back-link"><a href="<?php echo Mage::helper('customer')->getLoginUrl() ?>" class="back-link"><small>&leftarrow;</small> <?php echo $this->__('Login') ?></a></p>
            <a href="<?php echo Mage::helper('customer')->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot your password') ?></a>
        </div>
    </div>
</div>
<script type="text/javascript">
    callSocialLoginInterface();
    initializeRegisterRaasForm();
    initializeSocialRegisterRaasForm();
    show_birthdate_date_block();
    jQuery(document).ready(setTimeout(function(){jQuery('.magento-raas-loading-image-div').hide()},3000));
</script>
<?php }else{
    echo $activationBlockObj->activationErrorMessage();
}?>